### ISSUE TITLE
Please update org.kde.Platform runtime

### ISSUE THREAD

**Issue by LaurentBonnaud** [flathub/net.rpdev.OpenTodoList#53]
Hi,

here is the problem:

```
$ flatpak update
Looking for updates…

Info: runtime org.kde.Platform branch 6.4 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Info: applications using this runtime:
   net.rpdev.OpenTodoList
```

**Comment by mhoeher** [comment]
Thanks for letting me know. I'll take this up for the next version, see this [issue over on GitLab](https://gitlab.com/rpdev/opentodolist/-/issues/644).

**Comment by mhoeher** [comment]
And done - the app now targets the new runtime on the beta channel. The change will get active on stable with the next release (due end of the month).

**Comment by LaurentBonnaud** [comment]
I am looking forward to the end of the month :>.
Thanks!
