### ISSUE TITLE
.desktop file is missing

### ISSUE THREAD

**Issue by dgcampea** [flathub/net.rpdev.OpenTodoList#9]
Installing/reinstalling this via flathub I noticed that the old shortcut I had for it complained that the .desktop file is missing.
Verifying the contents of the `/var/lib/flatpak/exports/share/applications/` I confirmed that `net.rpdev.OpenTodoList.desktop` file is missing, which makes any DE unable to launch or find this application although it can be run via `flatpak run net.rpdev.OpenTodoList` via terminal.

**Comment by mhoeher** [comment]
Thanks for raising this issue. I guess this is due to the recent migration back to `qmake`. I'll try to get this fixed for the next release.

For reference, here is the issue used for this over on Gitlab: https://gitlab.com/rpdev/opentodolist/issues/277

**Comment by mhoeher** [comment]
The issue is fixed and the next release will include a proper `*.desktop` file again. I also just build a beta version (available on Flathub beta), which contains the fix, so if you can't wait, you can install that until the next official release.
